{{ if .Values.appsettings }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "WebApp.fullname" . | lower }}-appsettings
data:
  appsettings.json: |-
    {{- range (.Values.appsettings | b64dec) | toStrings }}
    {{- . | nindent 8 }}
    {{- end }}
{{- end}}