{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "WebApp.fullname" . | lower }}
  labels:
    {{- include "WebApp.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "WebApp.fullname" . | lower }}
  minReplicas: {{ max 2 .Values.autoscaling.minReplicas }} 
  maxReplicas: {{ max 2 .Values.autoscaling.minReplicas .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
