{{- if .Values.innagoVaultK8sRoleOperator.use -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "WebApp.fullname" . | lower | trunc 50 }}-vault-{{ randAlphaNum 5 | lower }}
  namespace: {{ .Release.Namespace }}
  annotations:
    innago.com/vault-k8s-role: ""
    argocd.argoproj.io/sync-options: ServerSideApply=true
data:
  serviceAccountName: "{{ include "WebApp.serviceAccountName" . }}"
  additionalPolicies: "{{ .Values.innagoVaultK8sRoleOperator.additionalPolicies | join "," }}"
{{- end -}}
