{{- if .Values.innagoVaultK8sRoleOperator.use -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "WebApp.fullname" . | lower | trunc 50 }}-vault-role
  namespace: {{ .Release.Namespace }}
  annotations:
    innago.com/vault-k8s-role: ""
    argocd.argoproj.io/sync-options: ServerSideApply=true
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-9"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  serviceAccountName: "{{ include "WebApp.serviceAccountName" . }}"
  additionalPolicies: "{{ .Values.innagoVaultK8sRoleOperator.additionalPolicies | join "," }}"
{{- end -}}
