{{- if .Values.migrationJob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "WebApp.migrationJobName" . }}
  labels:
    {{- include "WebApp.labels" . | nindent 4 }}
  annotations:
    {{- if not .Values.migrationJob.waitForItInInitContainer }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
    {{- with .Values.migrationJob.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
      {{- with .Values.migrationJob.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "WebAppMigrations.labels" . | nindent 8 }}

    spec:{{- with .Values.imagePullSecrets | default }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrationJob.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "WebApp.fullname" . | lower }}-migrations
          image: "{{ .Values.migrationJob.image.repository }}:{{ .Values.migrationJob.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.migrationJob.image.pullPolicy }}
          env:
            {{- with .Values.migrationJob.environmentVariables -}}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- with .Values.migrationJob.containerEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migrationJob.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.migrationJob.command }}
          command:
            {{- with .Values.migrationJob.command -}}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      restartPolicy: Never
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
