{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "WebApp.serviceAccountName" . | lower }}
  labels:
    {{- include "WebApp.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations (not .Values.migrationJob.waitForItInInitContainer) }}
  annotations:
    {{- if not .Values.migrationJob.waitForItInInitContainer }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "WebApp.serviceAccountName" . | lower }}
  labels:
    {{- include "WebApp.labels" . | nindent 4 }}
  {{- if not .Values.migrationJob.waitForItInInitContainer }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- end }}
rules:
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "WebApp.serviceAccountName" . | lower }}
  labels:
    {{- include "WebApp.labels" . | nindent 4 }}
  {{- if not .Values.migrationJob.waitForItInInitContainer }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "WebApp.serviceAccountName" . | lower }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "WebApp.serviceAccountName" . | lower }}
{{- end }}
