apiVersion: v1
kind: Service
metadata:
  name: {{ include "WebApp.fullname" . | lower }}
  labels:
    {{- include "WebApp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.additionalServicePorts }}
      {{- toYaml .Values.additionalServicePorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "WebApp.selectorLabels" . | nindent 4 }}
