{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "WebApp.serviceAccountName" . | lower }}
  labels:
    {{- include "WebApp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "WebApp.serviceAccountName" . | lower }}
  labels:
    {{- include "WebApp.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "WebApp.serviceAccountName" . | lower }}
  labels:
    {{- include "WebApp.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "WebApp.serviceAccountName" . | lower }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "WebApp.serviceAccountName" . | lower }}
{{- end }}
