name: merge-checks

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  sast:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: semgrep-action
        uses: semgrep/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d #v1
  secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    container:
      image: ghcr.io/gitleaks/gitleaks:latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: GitLeaks
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.SEMVER_TOKEN }}"
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          WORK_DIR="/__w/${{ github.repository_owner }}/${REPO_NAME}"
          CONTAINER_WORK_DIR="/__w/${REPO_NAME}/${REPO_NAME}"
          git config --global --add safe.directory "$WORK_DIR"
          git config --global --add safe.directory "$CONTAINER_WORK_DIR"
          gitleaks detect --verbose --source . --log-level trace
